config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get '/profile' => 'pages#profile'
  get '/manager' => 'pages#manager'
  get '/root' => 'pages#root'
  devise_for :users
  resources :employee_tasks	
  resources :employee_report_types
  resources :employee_reports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee_report.rb
class EmployeeReport < ApplicationRecord
  belongs_to :user
  belongs_to :employee_report_type
  has_many :employee_tasks, dependent: :destroy, dependent: :destroy
  def to_s
  	self.Report_Name
  end		
end

app/models/employee_report_type.rb
class EmployeeReportType < ApplicationRecord
  def to_s
  	self.Report_Type
  end
end

app/controllers/employee_reports_controller.rb
class EmployeeReportsController < ApplicationController
  before_action :set_employee_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /employee_reports
  # GET /employee_reports.json
  def index
    @employee_reports = current_user.employee_reports.all.order("created_at DESC")
  end

  # GET /employee_reports/1
  # GET /employee_reports/1.json
  def show
    # @task = EmployeeTask.where(EmployeeReport.ids == EmployeeTask.employee_report_id)
    # Model.all.select { |m| m.field == value }
    #@task = EmployeeTask.all.select { |t| t.employee_report_id == EmployeeReport.ids}
    #@task = EmployeeTask.pluck(:id, :Task_Name).where(:employee_report_id == EmployeeReport.ids)
    # @task = EmployeeTask.all.map(&:Task_Name)
  end

  # GET /employee_reports/new
  def new
    @employee_report = current_user.employee_reports.build
  end

  # GET /employee_reports/1/edit
  def edit
  end

  # POST /employee_reports
  # POST /employee_reports.json
  def create
    @employee_report = current_user.employee_reports.build(employee_report_params)

    respond_to do |format|
      if @employee_report.save
        format.html { redirect_to @employee_report, notice: 'Employee report was successfully created.' }
        format.json { render :show, status: :created, location: @employee_report }
      else
        format.html { render :new }
        format.json { render json: @employee_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_reports/1
  # PATCH/PUT /employee_reports/1.json
  def update
    respond_to do |format|
      if @employee_report.update(employee_report_params)
        format.html { redirect_to @employee_report, notice: 'Employee report was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_report }
      else
        format.html { render :edit }
        format.json { render json: @employee_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_reports/1
  # DELETE /employee_reports/1.json
  def destroy
    @employee_report.destroy
    respond_to do |format|
      format.html { redirect_to employee_reports_url, notice: 'Employee report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_report
      @employee_report = EmployeeReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_report_params
      params.require(:employee_report).permit(:Report_Name, :Report_Start_Date, :Report_End_Date, :employee_report_type_id, :user_id)
    end
end

app/helpers/employee_reports_helper.rb
module EmployeeReportsHelper
end

app/views/employee_reports/_form.html.erb
<%= simple_form_for(@employee_report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs row">
    <div class="col-xs-12 col-md-12">
      <%= f.input :Report_Name %>
    </div>  
    <div class="col-xs-12 col-md-12">
      <%= f.association :employee_report_type %>
    </div>
    <div class="col-xs-12 col-md-4 col-md-offset-2">  
      <%= f.input :Report_Start_Date %>
    </div>
    <div class="col-xs-12 col-md-4">  
      <%= f.input :Report_End_Date %>
    </div>  
  </div><hr>

  <div class="form-actions row">
    <div class="col-xs-12 col-md-12">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>  
  </div><br>
<% end %>

app/views/employee_reports/edit.html.erb
<br>
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Edit Employee Report</h1>
	</div>
	<div class="panel-body">
		<%= render 'form', employee_report: @employee_report %>
	</div>
</div>
<%= link_to 'Show', @employee_report, class: "btn btn-xs btn-info" %>
<%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>

app/views/employee_reports/index.html.erb
<h1>Employee Reports</h1><hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Report name</th>
      <th>Report start date</th>
      <th>Report end date</th>
      <th>Employee report type</th>
      <th>Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_reports.each do |employee_report| %>
      <tr>
        <td><%= link_to employee_report.Report_Name, employee_report %></td>
        <td><%= employee_report.Report_Start_Date %></td>
        <td><%= employee_report.Report_End_Date %></td>
        <td><%= employee_report.employee_report_type %></td>
        <td><%= employee_report.created_at %></td>
        <!-- <td><%= link_to 'Show', employee_report %></td> -->
        <td><%= link_to 'Edit Report', edit_employee_report_path(employee_report), class: "btn btn-xs btn-warning" %></td>
        <td><%= link_to 'Destroy Report', employee_report, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<%= link_to 'New Employee Report', new_employee_report_path %>

app/views/employee_reports/new.html.erb
<br>
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>New Employee Report</h1>
	</div>
	<div class="panel-body">
		<%= render 'form', employee_report: @employee_report %>
	</div>
</div>
<%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>

app/views/employee_reports/show.html.erb
<br>
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1 class="text-center"><%= @employee_report.Report_Name %></h1>
      </div>
      <div class="panel-body">

        <strong>Report start date:</strong>
        <%= @employee_report.Report_Start_Date %><br>

        <strong>Report end date:</strong>
        <%= @employee_report.Report_End_Date %><br>

        <strong>Employee report type:</strong>
        <%= @employee_report.employee_report_type %><br><br>

        <%= link_to 'Edit Report', edit_employee_report_path(@employee_report), class: "btn btn-xs btn-warning" %>
      </div>  
    </div>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <%= link_to "Add New Task", new_employee_task_path(:employee_report => @employee_report), class: "btn btn-primary btn-block" %>
  </div>
</div>

<hr>
<div class="row">
  <% @employee_report.employee_tasks.each do |task| %>
  	<div class="col-xs-12 col-md-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h4 class="text-center"><%= task.Task_Name %></h4>
        </div>
        <div class="panel-body">
      		<span class="text-primary">Task:</span> <%= task.id %><br>
      		<span class="text-primary">Report:</span> <%= task.employee_report %><br>
      		<span class="text-primary">Start:</span> <%= task.Task_Start_Date %><br>
      		<span class="text-primary">Due:</span> <%= task.Task_Due_Date %><hr>
          <%= link_to 'Show', task, class: "btn btn-xs btn-info" %>
        </div>  
    	</div>
    </div>	
  <% end %>
</div>

<div class="row">
  <div class="col-xs-12 col-md-12">
    <hr>
    <%= link_to 'Back', :back, class: "btn btn-xs btn-danger" %>
  </div>
</div>