config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get '/profile' => 'pages#profile'
  get '/manager' => 'pages#manager'
  get '/root' => 'pages#root'
  devise_for :users
  resources :employee_tasks	
  resources :employee_report_types
  resources :employee_reports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/employee_report_types_controller.rb
class EmployeeReportTypesController < ApplicationController
  before_action :set_employee_report_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /employee_report_types
  # GET /employee_report_types.json
  def index
    @employee_report_types = EmployeeReportType.all
  end

  # GET /employee_report_types/1
  # GET /employee_report_types/1.json
  def show
  end

  # GET /employee_report_types/new
  def new
    @employee_report_type = EmployeeReportType.new
  end

  # GET /employee_report_types/1/edit
  def edit
  end

  # POST /employee_report_types
  # POST /employee_report_types.json
  def create
    @employee_report_type = EmployeeReportType.new(employee_report_type_params)

    respond_to do |format|
      if @employee_report_type.save
        format.html { redirect_to @employee_report_type, notice: 'Employee report type was successfully created.' }
        format.json { render :show, status: :created, location: @employee_report_type }
      else
        format.html { render :new }
        format.json { render json: @employee_report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_report_types/1
  # PATCH/PUT /employee_report_types/1.json
  def update
    respond_to do |format|
      if @employee_report_type.update(employee_report_type_params)
        format.html { redirect_to @employee_report_type, notice: 'Employee report type was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_report_type }
      else
        format.html { render :edit }
        format.json { render json: @employee_report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_report_types/1
  # DELETE /employee_report_types/1.json
  def destroy
    @employee_report_type.destroy
    respond_to do |format|
      format.html { redirect_to employee_report_types_url, notice: 'Employee report type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_report_type
      @employee_report_type = EmployeeReportType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_report_type_params
      params.require(:employee_report_type).permit(:Report_Type)
    end
end

app/helpers/employee_report_types_helper.rb
module EmployeeReportTypesHelper
end

app/views/employee_report_types/_form.html.erb
<%= simple_form_for(@employee_report_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Report_Type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employee_report_types/edit.html.erb
<h1>Editing Employee Report Type</h1>

<%= render 'form', employee_report_type: @employee_report_type %>

<%= link_to 'Show', @employee_report_type %> |
<%= link_to 'Back', employee_report_types_path %>

app/views/employee_report_types/index.html.erb
<h1>Employee Report Types</h1><hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Report type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_report_types.each do |employee_report_type| %>
      <tr>
        <td><%= employee_report_type.Report_Type %></td>
        <td><%= link_to 'Show', employee_report_type %></td>
        <td><%= link_to 'Edit', edit_employee_report_type_path(employee_report_type) %></td>
        <td><%= link_to 'Destroy', employee_report_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee Report Type', new_employee_report_type_path %>

app/views/employee_report_types/new.html.erb
<h1>New Employee Report Type</h1>

<%= render 'form', employee_report_type: @employee_report_type %>

<%= link_to 'Back', employee_report_types_path %>

app/views/employee_report_types/show.html.erb
<p>
  <strong>Report type:</strong>
  <%= @employee_report_type.Report_Type %>
</p>

<%= link_to 'Edit', edit_employee_report_type_path(@employee_report_type) %> |
<%= link_to 'Back', employee_report_types_path %>