config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get '/profile' => 'pages#profile'
  get '/manager' => 'pages#manager'
  get '/root' => 'pages#root'
  devise_for :users
  resources :employee_tasks	
  resources :employee_report_types
  resources :employee_reports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee_task.rb
class EmployeeTask < ApplicationRecord
  belongs_to :employee_report
  def to_s
  	self.Task_Name
  end
end

app/controllers/employee_tasks_controller.rb
class EmployeeTasksController < ApplicationController
  before_action :set_employee_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /employee_tasks
  # GET /employee_tasks.json
  def index
    @employee_tasks = current_user.employee_tasks.all
  end

  # GET /employee_tasks/1
  # GET /employee_tasks/1.json
  def show
  end

  # GET /employee_tasks/new
  def new
    @employee_task = current_user.employee_tasks.build
    @employee_report = EmployeeReport.find(params[:employee_report])
  end

  # GET /employee_tasks/1/edit
  def edit
  end

  # POST /employee_tasks
  # POST /employee_tasks.json
  def create
    @employee_task = current_user.employee_tasks.build(employee_task_params)

    respond_to do |format|
      if @employee_task.save
        format.html { redirect_to @employee_task, notice: 'Employee task was successfully created.' }
        format.json { render :show, status: :created, location: @employee_task }
      else
        format.html { render :new }
        format.json { render json: @employee_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_tasks/1
  # PATCH/PUT /employee_tasks/1.json
  def update
    respond_to do |format|
      if @employee_task.update(employee_task_params)
        format.html { redirect_to @employee_task, notice: 'Employee task was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_task }
      else
        format.html { render :edit }
        format.json { render json: @employee_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_tasks/1
  # DELETE /employee_tasks/1.json
  def destroy
    @employee_task.destroy
    respond_to do |format|
      format.html { redirect_to employee_tasks_url, notice: 'Employee task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clone
    @clone = EmployeeTask.find(params[:id]).clone

    if @clone.save
      flash[:notice] = 'Item was successfully cloned.'
    else
      flash[:notice] = 'ERROR: Item can\'t be cloned.'
    end

    redirect_to(@employee_task)
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_task
      @employee_task = EmployeeTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_task_params
      params.require(:employee_task).permit(:Task_Name, :Task_Start_Date, :Task_Due_Date, :employee_report_id, :user_id, :Task_Description, :Task_Status)
    end
end

app/helpers/employee_tasks_helper.rb
module EmployeeTasksHelper
end

app/views/employee_tasks/_form.html.erb
<%= simple_form_for(@employee_task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="col-xs-12 col-md-12">
      <%= f.input :Task_Name %>
    </div>
    <div class="col-xs-12 col-md-12">  
      <%= f.input :Task_Description %>
    </div>
    <div class="col-xs-12 col-md-4 col-md-offset-2">  
      <%= f.input :Task_Start_Date %>
    </div>
    <div class="col-xs-12 col-md-4">  
      <%= f.input :Task_Due_Date %>
    </div>  
    <div class="col-xs-12 col-md-12">
      <%= f.input :Task_Status, as: :boolean, checked_value: 1, unchecked_value: 2, label: "Complete" %>
    </div>
      <!-- <span><%= f.association :employee_report %></span> -->
    <%= f.hidden_field :employee_report_id, :value => params[:employee_report] %>
  </div>
  <div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
  </div><br> 
<% end %>

app/views/employee_tasks/edit.html.erb
<h1>Editing Employee Task</h1>

<%= render 'form', employee_task: @employee_task %>

<%= link_to 'Show', @employee_task %> |
<%= link_to 'Back', employee_tasks_path %>

app/views/employee_tasks/index.html.erb
<h1>Employee Tasks</h1><hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Task name</th>
      <th>Description</th>
      <th>Task start date</th>
      <th>Task end date</th>
      <th>Employee report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_tasks.each do |employee_task| %>
      <tr>
        <td><%= employee_task.Task_Name %></td>
        <td><%= employee_task.Task_Description %></td>
        <td><%= employee_task.Task_Start_Date %></td>
        <td><%= employee_task.Task_Due_Date %></td>
        <td><%= employee_task.employee_report %></td>
        <td><%= link_to 'Show', employee_task %></td>
        <td><%= link_to 'Edit', edit_employee_task_path(employee_task) %></td>
        <td><%= link_to 'Destroy', employee_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employee_tasks/new.html.erb
<h1>New Employee Task</h1>

<%= render 'form', employee_task: @employee_task %>

<%= link_to 'Back', employee_tasks_path %>

app/views/employee_tasks/show.html.erb
<p>
  <strong>Task Name:</strong>
  <%= @employee_task.Task_Name %>
</p>

<p>
  <strong>Task Description:</strong>
  <%= @employee_task.Task_Description %>
</p>

<p>
  <strong>Task Start Date:</strong>
  <%= @employee_task.Task_Start_Date %>
</p>

<p>
  <strong>Task Due Date:</strong>
  <%= @employee_task.Task_Due_Date %>
</p>

<p>
  <strong>Task Status:</strong>
  <%= @employee_task.Task_Status %>
</p>

<p>
  <strong>Employee report:</strong>
  <%= @employee_task.employee_report %>
</p>

<%= link_to 'Edit', edit_employee_task_path(@employee_task) %> |
<%= link_to 'Back', employee_reports_path %>